In [0]:
import numpy as np

In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))


In [0]:
def sigmoid_derivative(x):
  return x * (1-x)

In [0]:
training_inp = np.array([[0,0,1],
                         [1,1,1],
                         [1,0,1],
                         [0,1,1]])

training_opt = np.array([[0,1,1,0]]).T

np.random.seed(1)

synaptic_wts = 2 * np.random.random((3,1)) - 1





In [40]:
print('Random synaptic weights before training: ')
print(synaptic_wts)

Random synaptic weights before training: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [0]:
for itr in range(10000):

  input_layer = training_inp

  outputs = sigmoid(np.dot(input_layer, synaptic_wts))

  error = training_opt - outputs

  adjustments = error * sigmoid_derivative(outputs)

  synaptic_wts += np.dot(input_layer.T, adjustments)

In [43]:
print('synaptic weights after training: ')
print(synaptic_wts)

synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


In [44]:
print('Outputs after training: ')
print(outputs)

Outputs after training: 
[[0.00966449]
 [0.99211957]
 [0.99358898]
 [0.00786506]]
